services:
  - type: web
    name: controlcore-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn controlcore.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: controlcore.onrender.com  # Will update once the domain is assigned
